---
- name: "Apache installation using docker"
  hosts: prod
  become: true
  pre_tasks:
    - name: Install required system packages
      yum:
        name:
          - epel-release
          - python3
          - python3-pip
          - python3-setuptools
          - docker
        state: present
      when: ansible_os_family == "RedHat"
    - name: Install Docker SDK for Python
      pip:
        name: docker    
  tasks:
    - name: "Installation paquets git et wget"
      yum:
        name:
          - wget
          - git
        state: present
      when: ansible_os_family == "RedHat"
    - name: Deploy Apache index.html
      ansible.builtin.template:
        src: index.j2
        dest: /var/www/html/index.html
        owner: admin
        group: admin
        mode: '0644'
    - name: Create Apache container
      docker_container:
        name: webapp
        image: httpd:2.4
        state: started
        restart_policy: always
        ports:
          - "80:80"
        volumes:
          - /var/www/html:/usr/local/apache2/htdocs
